version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sxexpo
    volumes:
      - ./mongo-local/init-mongo.js:/docker-entrypoint-initdb.d/0-init-mongo.js:ro
      - ./seeds/mongo/init-data.js:/docker-entrypoint-initdb.d/1-init-data.js:ro